#!/bin/bash

# TODO 
# Implementar comandos para facilicar o uso do docker-composer

# docker-compose-run create nodejs reactjs mongodb
# docker-compose-run down all
  
docker container rm -f $(docker container ls -a -q)      
docker image rm -f $(docker image ls -a -q)      
docker volume rm -f $(docker volume ls -q)   
docker network rm $(docker network ls -q)

# docker-compose up -d --build nginx php nodejs redis postgresql mariadb mongodb

# docker-compose up -d --build nodejs mongodb