# Stack Laravel/AngularJS with PostgresSQL
version: "3.7"

services:
    # Container NGINX ✔
    nginx:
        container_name: ${COMPANY_NAME}_nginx
        build:
            context: ${DOCKER_BUILDS_DIR}/nginx/
            args:
                - NGINX_VERSION=${NGINX_VERSION}
                - NGINX_APP_PORT=${NGINX_HOST_HTTP_APP_PORT}
                - NGINX_API_PORT=${NGINX_HOST_HTTP_API_PORT}
                - NGINX_HOST_APP_NAME=${APP_NAME}
                - NGINX_HOST_API_NAME=${API_NAME}
        volumes:
            - ${DOCKER_HTDOCS_DIR}/${APP_NAME}:/var/www/html/app
            - ${DOCKER_HTDOCS_DIR}/${API_NAME}:/var/www/html/api
            - ${DOCKER_STORAGE_DIR}/logs/nginx:/var/log/nginx
            - ${DOCKER_BUILDS_DIR}/${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HOST_HTTP_DEFAULT_PORT}:80"
            - "${NGINX_HOST_HTTPS_DEFAULT_PORT}:443"
            - "${NGINX_HOST_HTTP_APP_PORT}:8081"
            - "${NGINX_HOST_HTTP_API_PORT}:8082"
        links:
            - php
            - redis
        networks:
            - local_network

    # Container PHP-FPM ✔
    php:
        container_name: ${COMPANY_NAME}_php
        hostname: php
        build:
            context: ${DOCKER_BUILDS_DIR}/php-fpm/
            args:
                - PHP_FPM_VERSION=${PHP_FPM_VERSION}
                - PHP_FPM_ENV=${APPLICATION_ENV}
        ports:
            - "${PHP_FPM_PORT}:9000"
        expose:
            - "${PHP_FPM_PORT}"
        volumes:
            - ${DOCKER_STORAGE_DIR}/logs/php-fpm:/var/log/php
            - ${DOCKER_HTDOCS_DIR}/${API_NAME}:/var/www/html/api
        links:
            - redis
        networks:
            - local_network

    # Container POSTGRES ✔
    postgresql:
        container_name: ${COMPANY_NAME}_postgresql
        build:
            context: ${DOCKER_BUILDS_DIR}/postgresql
            args:
                - POSTGRES_VERSION=${POSTGRES_VERSION}
            dockerfile: Dockerfile
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - postgresql:/var/lib/postgresql
            - ${DOCKER_STORAGE_DIR}/logs/postgresql:/var/log/postgres
            - ${DOCKER_HTDOCS_DIR}/${API_NAME}/database/seeds:/home/db/seeds
            - ${DOCKER_HTDOCS_DIR}/${API_NAME}/database/migrations:/home/db/migrations
            - ${DOCKER_BUILDS_DIR}/postgresql/init.d:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - local_network

# Rede Local ✔
networks:
    local_network:
        driver: ${DOCKER_NETWORKS_DRIVER}

# Volumes do Docker Local ✔
volumes:
    postgresql:
        driver: ${DOCKER_VOLUMES_DRIVER}
